/** Declaration file generated by dts-gen */

export const metadata: {
    "Browser actions": string[];
    Events: string[];
    Helpers: string[];
    "Page actions": string[];
    "Proximity selectors": string[];
    Selectors: string[];
};

export function $(selector: any, args: any): any;

export function above(selector: any): any;

export function accept(): any;

export function alert(message: any, callback: any): void;

export function attach(filepath: any, to: any): any;

export function beforeunload(message: any, callback: any): void;

export function below(selector: any): any;

export function button(attrValuePairs: any, args: any): any;

export function checkBox(attrValuePairs: any, args: any): any;

export function clear(selector: any, options: any): any;

export function click(selector: any, options: any, args: any): any;

export function client(): void;

export function closeBrowser(): any;

export function closeTab(targetUrl: any): any;

export function comboBox(attrValuePairs: any, args: any): any;

export function confirm(message: any, callback: any): void;

export function contains(text: any, args: any): any;

export function dismiss(): any;

export function doubleClick(selector: any, options: any, args: any): any;

export function evaluate(selector: any, callback: any, options: any, ...args: any[]): any;

export function fileField(attrValuePairs: any, args: any): any;

export function focus(selector: any, options: any): any;

export function highlight(selector: any): any;

export function hover(selector: any, options: any): any;

export function image(attrValuePairs: any, args: any): any;

export function inputField(attrValuePairs: any, args: any): any;

export function intercept(requestUrl: any, option: any): any;

export function intervalSecs(secs: any): void;

export function into(e: any): void;

export function link(attrValuePairs: any, args: any): any;

export function listItem(attrValuePairs: any, args: any): any;

export function near(selector: any): any;

export function openBrowser(options: any): any;

export function openTab(targetUrl: any, options: any): any;

export function press(keys: any, options: any): any;

export function prompt(message: any, callback: any): void;

export function radioButton(attrValuePairs: any, args: any): any;

export function reload(url: any): any;

export function rightClick(selector: any, options: any, args: any): any;

export function screenshot(options: any): any;

export function scrollDown(e: any, px: any): any;

export function scrollLeft(e: any, px: any): any;

export function scrollRight(e: any, px: any): any;

export function scrollTo(selector: any, options: any): any;

export function scrollUp(e: any, px: any): any;

export function setViewPort(options: any): any;

export function switchTo(targetUrl: any): any;

export function text(text: any, args: any): any;

export function textField(attrValuePairs: any, args: any): any;

export function timeoutSecs(secs: any): void;

export function title(): any;

export function to(e: any): void;

export function toLeftOf(selector: any): any;

export function toRightOf(selector: any): any;

export function waitFor(time: any): any;

export function write(text: any, into: any, options: any): any;

export namespace contains {
    const prototype: {
    };

}

export namespace fileField {
    const prototype: {
    };

}

export namespace textField {
    const prototype: {
    };

}

export namespace waitFor {
    const prototype: {
    };

}

