[build]
  command = "npm install && npm run doc:starlight"
  publish = "packages/docs/dist"

[[redirects]]
  from = "/devices"
  to = "https://github.com/getgauge/taiko/blob/master/packages/taiko/lib/data/devices.js"
