name: Release on PR Merge
on: 
  pull_request:
    types: closed
jobs:
  release-and-bump-version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'SkipRelease')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Make Github release
      run: ./build/github_release.sh
    - name: Bump version
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'actions@github.com'
        npm version patch --no-git-tag-version | xargs -I {} git commit -am "Bumping up -> {}" && git push origin master
