name: taiko-tests

on: [push, pull_request]

jobs:
  unit-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: 12
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12
      - name: install
        run: |
          npm install
      - name: unit-tests
        run: |
          npm test

  functional-tests:
    needs: unit-tests
    name: NodeJS ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10,12]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: 12
      - name: install
        run: |
          npm install
      - name: functional-tests
        env:
          GAUGE_TELEMETRY_ENABLED: false
        run: |
          npm run test-functional
      - name: examples
        run: |
          npm run examples
