name: update-chromium
on:
  schedule:
    # cron job that will run 1st and 15th of every month by 12am
    - cron: '0 12 1,15 * *'

jobs:
  update-to-latest-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Setup
        run: |
          sudo apt-get update
           sudo apt-get install -y  libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libcups2 \
            libxrandr2 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libdrm-dev \
            libgbm-dev \
            libasound-dev

      - name: Get Chromium version and update
        run: |
          npm install
          node updateChromium.js
          revision=$(cat package.json | grep chromium_revision | awk '{print $2}' | sed 's/[",]//g')
          echo "REVISION=$revision" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GAUGEBOT_GITHUB_TOKEN }}
          branch: ${{format('{0}{1}', 'update-chromium',env.REVISION)}}
          commit-message: ${{format('{0}{1}','Update chromium to revision ', env.REVISION)}}
          title: ${{format('{0}{1}','Update chromium to revision ', env.REVISION)}}
